### ISSUE TITLE
Activate relative assets changed in v4.0.0

### ISSUE THREAD

**Issue by zheileman** [ministryofjustice/tech-docs-github-pages-publisher#126]
Hello,

As part of the recent refactor, the following line was removed from the [config.rb](https://github.com/ministryofjustice/tech-docs-github-pages-publisher/compare/v3.0.2...v4.0.0#diff-ced64b8b6dfa69a5939ae831c96e37b88e8266c37371a4d3b96759fb1ea147c8)

`activate :relative_assets`

New [config.rb](https://github.com/ministryofjustice/tech-docs-github-pages-publisher/blob/main/src/opt/publisher/config.rb) without the above declaration.

We believe this has caused issues with our tech docs site where before asset URLs were like this:
`<link href="stylesheets/manifest.css" rel="stylesheet" />`

And now with v4.0.0 are:
`<link href="/stylesheets/manifest.css" rel="stylesheet" />`

Our GitHub Pages are published to a path in `ministryofjustice.github.io`, they are not served from a custom domain.

Is there a way to get back or configure the old behaviour? I'm not 100% certain this is the reason as obviously v4.0.0 introduces other changes and bump to different dependencies but we believe this may be likely the cause.

Thank you.

**Comment by jacobwoffenden** [comment]
Hey @zheileman,

I'd not seen this issue after I published v4, apologies for not responding sooner!

I'm just in the process of creating v5, and tested with the following added to `config.rb`

```ruby
activate :relative_assets
set :relative_links, true
```

and it works as you'd expect

```html
<link href="stylesheets/manifest.css" rel="stylesheet" />
```

So I will add that back into the default `config.rb`

---

Until v5 is released, you can overwrite the packaged `config.rb` before running `/usr/local/bin/package` or `/usr/local/bin/preview`, for example:

```yaml
- name: Build
  id: build
  run: |
    mv config.rb /opt/publisher/config.rb
    /usr/local/bin/package
```
